### ISSUE TITLE
Evaluación de Medidas basadas en Exclusión Fija

### ISSUE THREAD

**Issue by Marianojgm86** [DIE-BG/HEMI#44]
Evaluación de medidas de exclusión fija (05/08/2021):

- [x] - Escenario A: Replicar el trabajo efectuado en 2020 - criterios básicos a dic-19
    - Datos hasta dic-19
    - Remuestreo por meses de ocurrencia
    - Parámetro (legacy): 2 cambios de base cada 3 años 
    - Tendencia: Random Walk 
    - Período completo
    - No hay que optimizar, solo replicar resultados de la página EMI-docs.

- [x] - Escenario B: Extender el trabajo efectuado en 2020 - criterios básicos a dic-20
    - Datos hasta dic-20
    - Remuestreo por meses de ocurrencia
    - Parámetro legacy: 2 cambios de base cada 3 años 
    - Tendencia: Random Walk 
    - Período completo
    - Sí hay que optimizar, al cambiar los datos pudieron cambiar óptimas

- [x] - Escenario C: Evaluación de criterios básicos a dic-20 - cambio de parámetro
    - Datos hasta 
        - dic-19, 
        - dic-20
    - Remuestreo por meses de ocurrencia
    - Parámetro cambios de base cada 5 años
    - Tendencia: Random Walk 
    - Período completo
    - Sí hay que optimizar, al cambiar los datos pudieron cambiar óptimas.

- [ ] - Escenario D: Evaluación de criterios básicos a dic-20 - remuestreo de bloques 
    - Datos hasta 
        - dic-19, 
        - dic-20
    - Remuestreo bloques estacionarios
    - Parámetro: 
        - legacy: 2 cambios de base cada 3 años,
        - cambios de base cada 5 años
    - Tendencia: Random Walk 
    - Período completo
    - Sí hay que optimizar, al cambiar los datos pudieron cambiar óptimas.

**Comment by r2cp** [comment]
Hola, @Marianojgm86, por favor utilizar los siguientes criterios de evaluación: 

- Período de evaluación: completo
- Período final de evaluación: diciembre de 2020
- Estadístico de evaluación: MSE
- Número de simulaciones: 125,000
- Función de tendencia: caminata aleatoria calibrada
- Trayectoria de inflación paramétrica: Variación interanual del IPC con cambios de base
- Método de remuestreo: Block bootstrap estacionario con tamaño de bloque 36 y metodología de remuestreo por meses de ocurrencia.
