### ISSUE TITLE
Añadir otros parámetros al SimConfig

### ISSUE THREAD

**Issue by m4wnn** [DIE-BG/HEMI#68]
¿Se pueden añadir otros parámetros al [``SimConfig``](https://github.com/DIE-BG/HEMI/blob/077301ec0b46f9e3e826cee93027c5ec459bd9d5/src/InflationEvalTools/src/config/SimConfig.jl#L46) ? 

Esto para que``evalsim``, ``makesim`` y ``run_batch`` puedan recibir un diccionario con variantes que incluyan la data, parámetro de inflación y semilla.

**Comment by m4wnn** [comment]
Viendo la función ``run_batch`` creo que también ayudaría a agregar el ``enddate`` y el parámetro al [nombre de los resultados](https://github.com/DIE-BG/HEMI/blob/077301ec0b46f9e3e826cee93027c5ec459bd9d5/src/InflationEvalTools/src/simulate/simutils.jl#L219).

**Comment by m4wnn** [comment]
> En main ya hay algo similar, se trabajó ayer. Creo que no incluye todo lo que mencionas pero una buena parte si.

Es cierto, ya tiene agregado el [parámetro de inflación](https://github.com/DIE-BG/HEMI/blob/077301ec0b46f9e3e826cee93027c5ec459bd9d5/src/InflationEvalTools/src/config/SimConfig.jl#L54).

**Comment by Marianojgm86** [comment]
En cuanto a la semilla, es parámetro opcional desde run_batch y entiendo que, una vez definida, no debiera variar con la configuración (pero los que han trabajado eso son ustedes jaja)

**Comment by m4wnn** [comment]
> En cuanto a la semilla, es parámetro opcional desde run_batch y entiendo que, una vez definida, no debiera variar con la configuración (pero los que han trabajado eso son ustedes jaja)

Tenés razón. Ahora que lo pienso, en la última evaluación lo único que hicimos fue ponernos de acuerdo en usar una única semilla en toda la evaluación. 

En la evaluación pasada recuerdo que en la configuración también se incluía la *fecha final de los datos* y el *periodo de evaluación*. Esto porque se nos solicitó unos escenarios de sensibilidad que seguramente volverán a pedir.

**Comment by r2cp** [comment]
La semilla ya fue idiosincráticamente definida por defecto en `DEFAULT_SEED` en `InflationEvalTools`. No es necesario proveer el parámetro opcional al simular. 

Un par de comentarios de lo que hace falta: 
- Creo que sería bueno agregar el campo de fecha final en los resultados. Esto está barato de hacer, podrías abrir un issue. 

- Lo de los períodos de evaluación no ha sido resuelto todavía. Es cierto, necesitamos generar esos resultados para los análisis de sensibildad. Creo que se podría atacar este problema en [esta sección](https://github.com/DIE-BG/HEMI/blob/f857ffc4dc4d49778e4e26989850a64da1f9981d/src/InflationEvalTools/src/simulate/simutils.jl#L239-L246) de `run_batch` y no mezclar este problema con la pureza de `evalsim` y `makesim`, que son las más útiles para obtener los resultados principales o de criterios básicos. De igual forma, sería bueno generar algunas gráficas de diagnóstico, como la distribución del error y las trayectorias promedio vs. paramétrica. Creo que igual se podrían poner en esta misma sección de `run_batch` y utilizar parámetros para añadir la opción de generar dichos resultados.
