### ISSUE TITLE
Añadir fecha final de los datos al nombre del archivo con resultados de evaluación

### ISSUE THREAD

**Issue by m4wnn** [DIE-BG/HEMI#69]
Como referencia, dejo la ubicación en ``run_batch`` donde se [almacenan los resultados](https://github.com/DIE-BG/HEMI/blob/f857ffc4dc4d49778e4e26989850a64da1f9981d/src/InflationEvalTools/src/simulate/simutils.jl#L246).

**Comment by Marianojgm86** [comment]
Ojo con los caracteres del string de fecha que agregues. El formato debe estar limitado a los caracteres posibles para nombres de archivos (las "/" me parece que no pueden usarse)

**Comment by r2cp** [comment]
Ojo con la extensión de `DrWatson.savename` en [esta sección](https://github.com/DIE-BG/HEMI/blob/f857ffc4dc4d49778e4e26989850a64da1f9981d/src/InflationEvalTools/src/config/SimConfig.jl#L145-L149)

**Comment by Marianojgm86** [comment]
Ojo también con la longitud final del nombre. Estoy en pruebas con la inflación de exclusión fija (tiene un hash en el tag_name) y ya con el nombre de la ruta y el nombre del archivo se pasa de los 260 caracteres permitidos.
